/* jshint -W079 */
var mockData = (function() {
    return {
        getMockMetadata: getMockMetadata,
        getMockUser: getMockUser
    };

    function getMockMetadata() {
        return {
            metadataVersion: '1.0.5',
            namingConvetion: 'camelCase',
            localQueryComparisonOptions: 'caseInsensitiveSQL',
            dataServices: [{
                serviceName: 'breeze/',
                hasServerMetadata: true,
                useJsonp: false
            }],
            structuralTypes: [{

                shortName: 'User',
                namespace: 'Model',
                autoGeneratedKeyType: 'Identity',
                defaultResourceName: 'User',
                dataProperties: [{
                    nameOnServer: 'id',
                    dataType: 'Int32',
                    isPartOfKey: true,
                    isNullable: false
                }, {
                    name: 'firstName',
                    dataType: 'String',
                    displayName: 'First Name'
                }, {
                    name: 'lastName',
                    dataType: 'String',
                    displayName: 'Last Name'
                }, {
                    name: 'userName',
                    dataType: 'String',
                    isNullable: false,
                    maxLength: 18,
                    validators: [{
                        name: 'required'
                    }, {
                        maxLength: 18,
                        name: 'maxLength'
                    }],
                    displayName: 'Username'
                }, {
                    name: 'email',
                    dataType: 'String',
                    displayName: 'E-Mail'
                }]
            }],
            resourceEntityTypeMap: {
                User: 'User:#Model'
            }
        };
    }

    function getMockUser() {
        return [{
            id: 1,
            firstName: 'John',
            lastName: 'Doe',
            userName: 'joe'
        }];
    }

})();
